<?php
/**
 * Copyright (c) 2011 Andreas Heigl<andreas@heigl.org
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 * DEALINGS IN THE SOFTWARE.
 */
?><?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html>
	<head>
		<title>Gallery</title>
		<base href="http://development.local/gallery/src/public/"/>
<?php echo $this->headTitle() ?>
		<link rel="stylesheet" type="text/css" href="inc/css/gallery.css"/>
		<link rel="stylesheet" type="text/css" href="inc/lib/lightbox/css/lightbox.css"/>
	</head>
	<body>
		<?php echo $this->render('header.phtml');?>
		<?php echo $this->layout()->content; ?>
		<?php echo $this->render('footer.phtml');?>
	</body>
</html>
