<?php
/**
 * Copyright (c) 2011 Andreas Heigl<andreas@heigl.org
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 * DEALINGS IN THE SOFTWARE.
 */
?><ul id="paths">
<?php foreach ( $this->directories as $dir => $name ) { ?>
<li>
	<a href="index/index/path/<?php echo urlencode($dir); ?>"><?php echo $name;?></a>
</li>
<?php } ?>
</ul>
<ul id="images">
<?php foreach ($this->images as $img => $name){?>
<li>
	<table>
		<tr>
			<td class="imagecontainer">
			<a href="image/lightbox?path=<?php echo urlencode($img);?>" title="<?php echo $name; ?>" rel="lightbox[<?php echo dirname($img);?>]">
	<img src="image/show?path=<?php echo urlencode($img);?>" alt="<?php echo $name; ?>" rel="lightbox"/>
				</a>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $name; ?>
			</td>
		</tr>
		<tr>
			<td>
				<a class="basketadd icon" target="myBasket" href="basket/add/id/1/img/<?php echo base64_encode($img);?>">
					<?php echo $this->translate('Add to basket'); ?>
				</a>
			</td>
		</tr>
	</table>
</li>
<?php } ?>
</ul>
